Feature branch milestone.
Nowembabazi/To-do pull request #1
Opened 2022-10-17 18:37 UTC by Nowembabazi

##In this project I achieved the following;
-I add functionality to this project.
-Used webpack for this project.
-used index.html to the project.
-[Add functionality to add and remove task]

2022-10-19 03:28 UTC, blase147 requested changes
You did a great job here!! Your code is DRY and KISS.
You followed HTML and JavaScript best practices and clearly defined module functions. 
After you fix the highlighted issues in your README.md file you can then merge PR.

2022-10-19 03:28 UTC, blase147 commented on README.md
>  ## Live Demo (if available)
I suggest you update this link to point correctly to the live page. At the moment this link has error

2022-10-19 03:28 UTC, blase147 commented on README.md
> -### Run tests
You may try to remove unnecessary or unused  headings to keep your READ.md file clean

2022-10-19 03:28 UTC, blase147 commented on README.md
> -- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
These links seem not to be correct. You may edit them to reflect your individual social media links. You can also remove the second author lineif there was no second author

2022-10-19 03:28 UTC, blase147 commented on src/index.js
> +import _ from "lodash";
This import statement may no longer be useful here as it may have only been used for demonstration purposes and not for the main project

2022-10-19 03:28 UTC, blase147 commented on src/index.js
> +    myTask.value = "";
Optional fix!!
This variable declaration could look better when place at the top of the function

2022-10-21 05:05 UTC, Nowembabazi commented on src/index.js
> +    myTask.value = "";
Thank you for the feedback

2022-10-21 05:16 UTC, Nowembabazi commented on README.md
> -- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
changes have been made in the future branch

2022-10-21 05:17 UTC, Nowembabazi commented on README.md
> -### Run tests
adjustments were also made in the feature branch.

2022-10-21 05:18 UTC, merged

2022-10-21 05:18 UTC, Nowembabazi commented
Thanks for te feedback.